const BuildingData = [
  {
    Building: "2",
    Unit: "101",
    Floor: "1",
    Type: "3 BHK Prime",
    Status: "Sold",
  },
  {
    Building: "3",
    Unit: "101",
    Floor: "1",
    Type: "2 BHK Grand",
    Status: "Sold",
  },
  {
    Building: "2",
    Unit: "102",
    Floor: "1",
    Type: "4 BHK Supreme",
    Status: "Sold",
  },
  {
    Building: "1B",
    Unit: "102",
    Floor: "1",
    Type: "3bhk Duplex Grand",
    Status: "Sold",
  },
  {
    Building: "1A",
    Unit: "102",
    Floor: "1",
    Type: "3bhk Duplex Royal",
    Status: "Sold",
  },
  {
    Building: "3",
    Unit: "102",
    Floor: "1",
    Type: "2 BHK Prime",
    Status: "Sold",
  },
  {
    Building: "1B",
    Unit: "103",
    Floor: "1",
    Type: "3bhk Duplex Grand",
    Status: "Sold",
  },
  {
    Building: "1A",
    Unit: "103",
    Floor: "1",
    Type: "3bhk Duplex Royal",
    Status: "Sold",
  },
  {
    Building: "2",
    Unit: "103",
    Floor: "1",
    Type: "3 BHK Prime",
    Status: "Sold",
  },
  {
    Building: "3",
    Unit: "103",
    Floor: "1",
    Type: "2 BHK Prime",
    Status: "Sold",
  },
  {
    Building: "3",
    Unit: "104",
    Floor: "1",
    Type: "2 BHK Royal",
    Status: "Sold",
  },
  {
    Building: "1B",
    Unit: "104",
    Floor: "1",
    Type: "2bhk Duplex Grand",
    Status: "Sold",
  },
  {
    Building: "1A",
    Unit: "104",
    Floor: "1",
    Type: "2bhk Duplex Royal",
    Status: "Sold",
  },
  {
    Building: "1B",
    Unit: "105",
    Floor: "1",
    Type: "2bhk Duplex Grand",
    Status: "Sold",
  },
  {
    Building: "3",
    Unit: "105",
    Floor: "1",
    Type: "2 BHK Grand",
    Status: "Sold",
  },
  {
    Building: "2",
    Unit: "105",
    Floor: "1",
    Type: "3 BHK Grand",
    Status: "Sold",
  },
  {
    Building: "1A",
    Unit: "105",
    Floor: "1",
    Type: "2bhk Duplex Royal",
    Status: "Sold",
  },
  {
    Building: "3",
    Unit: "106",
    Floor: "1",
    Type: "2 BHK Prime",
    Status: "Sold",
  },
  {
    Building: "1B",
    Unit: "106",
    Floor: "1",
    Type: "3bhk Duplex Grand",
    Status: "Sold",
  },
  {
    Building: "1A",
    Unit: "106",
    Floor: "1",
    Type: "3bhk Duplex Royal",
    Status: "Sold",
  },
  {
    Building: "2",
    Unit: "106",
    Floor: "1",
    Type: "3 BHK Grand",
    Status: "Sold",
  },
  {
    Building: "1B",
    Unit: "107",
    Floor: "1",
    Type: "3bhk Duplex Grand",
    Status: "Sold",
  },
  {
    Building: "1A",
    Unit: "107",
    Floor: "1",
    Type: "3bhk Duplex Royal",
    Status: "Sold",
  },
  {
    Building: "1A",
    Unit: "108",
    Floor: "1",
    Type: "2bhk Duplex Royal",
    Status: "Sold",
  },
  {
    Building: "1B",
    Unit: "108",
    Floor: "1",
    Type: "2bhk Duplex Grand",
    Status: "Sold",
  },
  {
    Building: "3",
    Unit: "201",
    Floor: "2",
    Type: "2 BHK Grand",
    Status: "Sold",
  },
  {
    Building: "1A",
    Unit: "201",
    Floor: "2",
    Type: "2bhk Duplex Royal",
    Status: "Sold",
  },
  {
    Building: "2",
    Unit: "201",
    Floor: "2",
    Type: "3 BHK Prime",
    Status: "Sold",
  },
  {
    Building: "1B",
    Unit: "201",
    Floor: "2",
    Type: "2bhk Duplex Grand",
    Status: "Sold",
  },
  {
    Building: "2",
    Unit: "202",
    Floor: "2",
    Type: "4 BHK Supreme",
    Status: "Sold",
  },
  {
    Building: "1A",
    Unit: "202",
    Floor: "2",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "202",
    Floor: "2",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "202",
    Floor: "2",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "203",
    Floor: "2",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "203",
    Floor: "2",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "203",
    Floor: "2",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "203",
    Floor: "2",
    Type: "2 BHK Prime",
    Status: "Sold",
  },
  {
    Building: "1A",
    Unit: "204",
    Floor: "2",
    Type: "2bhk Duplex Royal",
    Status: "Sold",
  },
  {
    Building: "2",
    Unit: "204",
    Floor: "2",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "204",
    Floor: "2",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "204",
    Floor: "2",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "205",
    Floor: "2",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "205",
    Floor: "2",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "205",
    Floor: "2",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "205",
    Floor: "2",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "206",
    Floor: "2",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "206",
    Floor: "2",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "206",
    Floor: "2",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "206",
    Floor: "2",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "207",
    Floor: "2",
    Type: "3bhk Duplex Grand",
    Status: "Sold",
  },
  {
    Building: "1A",
    Unit: "207",
    Floor: "2",
    Type: "3bhk Duplex Royal",
    Status: "Sold",
  },
  {
    Building: "1B",
    Unit: "208",
    Floor: "2",
    Type: "2bhk Duplex Grand",
    Status: "Sold",
  },
  {
    Building: "1A",
    Unit: "208",
    Floor: "2",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "301",
    Floor: "3",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "301",
    Floor: "3",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "301",
    Floor: "3",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "301",
    Floor: "3",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "302",
    Floor: "3",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "302",
    Floor: "3",
    Type: "3bhk Duplex Royal",
    Status: "Sold",
  },
  {
    Building: "1B",
    Unit: "302",
    Floor: "3",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "302",
    Floor: "3",
    Type: "4 BHK Supreme",
    Status: "Sold",
  },
  {
    Building: "3",
    Unit: "303",
    Floor: "3",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "303",
    Floor: "3",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "303",
    Floor: "3",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "303",
    Floor: "3",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "304",
    Floor: "3",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "304",
    Floor: "3",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "304",
    Floor: "3",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "304",
    Floor: "3",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "305",
    Floor: "3",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "305",
    Floor: "3",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "305",
    Floor: "3",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "305",
    Floor: "3",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "306",
    Floor: "3",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "306",
    Floor: "3",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "306",
    Floor: "3",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "306",
    Floor: "3",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "307",
    Floor: "3",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "307",
    Floor: "3",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "308",
    Floor: "3",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "308",
    Floor: "3",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "401",
    Floor: "4",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "401",
    Floor: "4",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "401",
    Floor: "4",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "401",
    Floor: "4",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "402",
    Floor: "4",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "402",
    Floor: "4",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "402",
    Floor: "4",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "402",
    Floor: "4",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "403",
    Floor: "4",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "403",
    Floor: "4",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "403",
    Floor: "4",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "403",
    Floor: "4",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "404",
    Floor: "4",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "404",
    Floor: "4",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "404",
    Floor: "4",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "404",
    Floor: "4",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "405",
    Floor: "4",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "405",
    Floor: "4",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "405",
    Floor: "4",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "405",
    Floor: "4",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "406",
    Floor: "4",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "406",
    Floor: "4",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "406",
    Floor: "4",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "406",
    Floor: "4",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "407",
    Floor: "4",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "407",
    Floor: "4",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "408",
    Floor: "4",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "408",
    Floor: "4",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "501",
    Floor: "5",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "501",
    Floor: "5",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "501",
    Floor: "5",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "501",
    Floor: "5",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "502",
    Floor: "5",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "502",
    Floor: "5",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "502",
    Floor: "5",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "502",
    Floor: "5",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "503",
    Floor: "5",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "503",
    Floor: "5",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "503",
    Floor: "5",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "503",
    Floor: "5",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "504",
    Floor: "5",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "504",
    Floor: "5",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "504",
    Floor: "5",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "504",
    Floor: "5",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "505",
    Floor: "5",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "505",
    Floor: "5",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "505",
    Floor: "5",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "505",
    Floor: "5",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "506",
    Floor: "5",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "506",
    Floor: "5",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "506",
    Floor: "5",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "506",
    Floor: "5",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "507",
    Floor: "5",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "507",
    Floor: "5",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "508",
    Floor: "5",
    Type: "1bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "508",
    Floor: "5",
    Type: "1bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "601",
    Floor: "6",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "601",
    Floor: "6",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "601",
    Floor: "6",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "601",
    Floor: "6",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "602",
    Floor: "6",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "602",
    Floor: "6",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "602",
    Floor: "6",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "602",
    Floor: "6",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "603",
    Floor: "6",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "603",
    Floor: "6",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "603",
    Floor: "6",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "603",
    Floor: "6",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "604",
    Floor: "6",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "604",
    Floor: "6",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "604",
    Floor: "6",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "604",
    Floor: "6",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "605",
    Floor: "6",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "605",
    Floor: "6",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "605",
    Floor: "6",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "605",
    Floor: "6",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "606",
    Floor: "6",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "606",
    Floor: "6",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "606",
    Floor: "6",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "606",
    Floor: "6",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "607",
    Floor: "6",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "607",
    Floor: "6",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "608",
    Floor: "6",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "608",
    Floor: "6",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "701",
    Floor: "7",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "701",
    Floor: "7",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "701",
    Floor: "7",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "701",
    Floor: "7",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "702",
    Floor: "7",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "702",
    Floor: "7",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "702",
    Floor: "7",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "702",
    Floor: "7",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "703",
    Floor: "7",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "703",
    Floor: "7",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "703",
    Floor: "7",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "703",
    Floor: "7",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "704",
    Floor: "7",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "704",
    Floor: "7",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "704",
    Floor: "7",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "704",
    Floor: "7",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "705",
    Floor: "7",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "705",
    Floor: "7",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "705",
    Floor: "7",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "705",
    Floor: "7",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "706",
    Floor: "7",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "706",
    Floor: "7",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "706",
    Floor: "7",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "706",
    Floor: "7",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "707",
    Floor: "7",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "707",
    Floor: "7",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "708",
    Floor: "7",
    Type: "1bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "708",
    Floor: "7",
    Type: "1bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "801",
    Floor: "8",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "801",
    Floor: "8",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "801",
    Floor: "8",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "801",
    Floor: "8",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "802",
    Floor: "8",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "802",
    Floor: "8",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "802",
    Floor: "8",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "802",
    Floor: "8",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "803",
    Floor: "8",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "803",
    Floor: "8",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "803",
    Floor: "8",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "803",
    Floor: "8",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "804",
    Floor: "8",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "804",
    Floor: "8",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "804",
    Floor: "8",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "804",
    Floor: "8",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "805",
    Floor: "8",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "805",
    Floor: "8",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "805",
    Floor: "8",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "805",
    Floor: "8",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "806",
    Floor: "8",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "806",
    Floor: "8",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "806",
    Floor: "8",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "806",
    Floor: "8",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "807",
    Floor: "8",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "807",
    Floor: "8",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "808",
    Floor: "8",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "808",
    Floor: "8",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "901",
    Floor: "9",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "901",
    Floor: "9",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "901",
    Floor: "9",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "901",
    Floor: "9",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "902",
    Floor: "9",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "902",
    Floor: "9",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "902",
    Floor: "9",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "902",
    Floor: "9",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "903",
    Floor: "9",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "903",
    Floor: "9",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "903",
    Floor: "9",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "904",
    Floor: "9",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "904",
    Floor: "9",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "904",
    Floor: "9",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "904",
    Floor: "9",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "905",
    Floor: "9",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "905",
    Floor: "9",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "905",
    Floor: "9",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "905",
    Floor: "9",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "906",
    Floor: "9",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "906",
    Floor: "9",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "906",
    Floor: "9",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "906",
    Floor: "9",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "907",
    Floor: "9",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "907",
    Floor: "9",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "908",
    Floor: "9",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "908",
    Floor: "9",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1001",
    Floor: "10",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1001",
    Floor: "10",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1001",
    Floor: "10",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1001",
    Floor: "10",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1002",
    Floor: "10",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1002",
    Floor: "10",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1002",
    Floor: "10",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1002",
    Floor: "10",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1003",
    Floor: "10",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1003",
    Floor: "10",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1003",
    Floor: "10",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1003",
    Floor: "10",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1004",
    Floor: "10",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1004",
    Floor: "10",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1004",
    Floor: "10",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1004",
    Floor: "10",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1005",
    Floor: "10",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1005",
    Floor: "10",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1005",
    Floor: "10",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1005",
    Floor: "10",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1006",
    Floor: "10",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1006",
    Floor: "10",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1006",
    Floor: "10",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1006",
    Floor: "10",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1007",
    Floor: "10",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1007",
    Floor: "10",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1008",
    Floor: "10",
    Type: "1bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1008",
    Floor: "10",
    Type: "1bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1101",
    Floor: "11",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1101",
    Floor: "11",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1101",
    Floor: "11",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1101",
    Floor: "11",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1102",
    Floor: "11",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1102",
    Floor: "11",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1102",
    Floor: "11",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1102",
    Floor: "11",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1103",
    Floor: "11",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1103",
    Floor: "11",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1103",
    Floor: "11",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1103",
    Floor: "11",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1104",
    Floor: "11",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1104",
    Floor: "11",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1104",
    Floor: "11",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1104",
    Floor: "11",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1105",
    Floor: "11",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1105",
    Floor: "11",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1105",
    Floor: "11",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1105",
    Floor: "11",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1106",
    Floor: "11",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1106",
    Floor: "11",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1106",
    Floor: "11",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1106",
    Floor: "11",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1107",
    Floor: "11",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1107",
    Floor: "11",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1108",
    Floor: "11",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1108",
    Floor: "11",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1201",
    Floor: "12",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1201",
    Floor: "12",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1201",
    Floor: "12",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1201",
    Floor: "12",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1202",
    Floor: "12",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1202",
    Floor: "12",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1202",
    Floor: "12",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1202",
    Floor: "12",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1203",
    Floor: "12",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1203",
    Floor: "12",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1203",
    Floor: "12",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1203",
    Floor: "12",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1204",
    Floor: "12",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1204",
    Floor: "12",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1204",
    Floor: "12",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1204",
    Floor: "12",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1205",
    Floor: "12",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1205",
    Floor: "12",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1205",
    Floor: "12",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1205",
    Floor: "12",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1206",
    Floor: "12",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1206",
    Floor: "12",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1206",
    Floor: "12",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1206",
    Floor: "12",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1207",
    Floor: "12",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1207",
    Floor: "12",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1208",
    Floor: "12",
    Type: "1bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1208",
    Floor: "12",
    Type: "1bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1401",
    Floor: "14",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1401",
    Floor: "14",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1401",
    Floor: "14",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1401",
    Floor: "14",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1402",
    Floor: "14",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1402",
    Floor: "14",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1402",
    Floor: "14",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1402",
    Floor: "14",
    Type: "3bhk Duplex Royal Xtend",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1403",
    Floor: "14",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1403",
    Floor: "14",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1403",
    Floor: "14",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1403",
    Floor: "14",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1404",
    Floor: "14",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1404",
    Floor: "14",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1404",
    Floor: "14",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1404",
    Floor: "14",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1405",
    Floor: "14",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1405",
    Floor: "14",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1405",
    Floor: "14",
    Type: "2bhk Duplex Royal Xtend",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1405",
    Floor: "14",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1406",
    Floor: "14",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1406",
    Floor: "14",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1406",
    Floor: "14",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1406",
    Floor: "14",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1407",
    Floor: "14",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1407",
    Floor: "14",
    Type: "3bhk Duplex Grand Xtend",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1408",
    Floor: "14",
    Type: "2bhk Duplex Royal Xtend",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1408",
    Floor: "14",
    Type: "2bhk Duplex Grand Xtend",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1501",
    Floor: "15",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1501",
    Floor: "15",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1501",
    Floor: "15",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1501",
    Floor: "15",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1502",
    Floor: "15",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1502",
    Floor: "15",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1502",
    Floor: "15",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1502",
    Floor: "15",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1503",
    Floor: "15",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1503",
    Floor: "15",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1503",
    Floor: "15",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1504",
    Floor: "15",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1504",
    Floor: "15",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1504",
    Floor: "15",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1504",
    Floor: "15",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1505",
    Floor: "15",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1505",
    Floor: "15",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1505",
    Floor: "15",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1505",
    Floor: "15",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1506",
    Floor: "15",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1506",
    Floor: "15",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1506",
    Floor: "15",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1506",
    Floor: "15",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1507",
    Floor: "15",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1507",
    Floor: "15",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1508",
    Floor: "15",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1508",
    Floor: "15",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1601",
    Floor: "16",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1601",
    Floor: "16",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1601",
    Floor: "16",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1601",
    Floor: "16",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1602",
    Floor: "16",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1602",
    Floor: "16",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1602",
    Floor: "16",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1602",
    Floor: "16",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1603",
    Floor: "16",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1603",
    Floor: "16",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1603",
    Floor: "16",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1603",
    Floor: "16",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1604",
    Floor: "16",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1604",
    Floor: "16",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1604",
    Floor: "16",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1604",
    Floor: "16",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1605",
    Floor: "16",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1605",
    Floor: "16",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1605",
    Floor: "16",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1605",
    Floor: "16",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1606",
    Floor: "16",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1606",
    Floor: "16",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1606",
    Floor: "16",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1606",
    Floor: "16",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1607",
    Floor: "16",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1607",
    Floor: "16",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1608",
    Floor: "16",
    Type: "1bhk Duplex Royal",
    Status: "Sold",
  },
  {
    Building: "1B",
    Unit: "1608",
    Floor: "16",
    Type: "1bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1701",
    Floor: "17",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1701",
    Floor: "17",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1701",
    Floor: "17",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1701",
    Floor: "17",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1702",
    Floor: "17",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1702",
    Floor: "17",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1702",
    Floor: "17",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1702",
    Floor: "17",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1703",
    Floor: "17",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1703",
    Floor: "17",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1703",
    Floor: "17",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1703",
    Floor: "17",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1704",
    Floor: "17",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1704",
    Floor: "17",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1704",
    Floor: "17",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1704",
    Floor: "17",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1705",
    Floor: "17",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1705",
    Floor: "17",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1705",
    Floor: "17",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1705",
    Floor: "17",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1706",
    Floor: "17",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1706",
    Floor: "17",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1706",
    Floor: "17",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1706",
    Floor: "17",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1707",
    Floor: "17",
    Type: "3bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1707",
    Floor: "17",
    Type: "3bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1A",
    Unit: "1708",
    Floor: "17",
    Type: "2bhk Duplex Royal",
    Status: "Unsold",
  },
  {
    Building: "1B",
    Unit: "1708",
    Floor: "17",
    Type: "2bhk Duplex Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1801",
    Floor: "18",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1801",
    Floor: "18",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1802",
    Floor: "18",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1802",
    Floor: "18",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1803",
    Floor: "18",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1803",
    Floor: "18",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1804",
    Floor: "18",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1804",
    Floor: "18",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1805",
    Floor: "18",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1805",
    Floor: "18",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1806",
    Floor: "18",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1806",
    Floor: "18",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1901",
    Floor: "19",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1901",
    Floor: "19",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1902",
    Floor: "19",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1902",
    Floor: "19",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1903",
    Floor: "19",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1903",
    Floor: "19",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1904",
    Floor: "19",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1904",
    Floor: "19",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1905",
    Floor: "19",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1905",
    Floor: "19",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "1906",
    Floor: "19",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "1906",
    Floor: "19",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2001",
    Floor: "20",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2001",
    Floor: "20",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2002",
    Floor: "20",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2002",
    Floor: "20",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2003",
    Floor: "20",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2004",
    Floor: "20",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2004",
    Floor: "20",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2005",
    Floor: "20",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2005",
    Floor: "20",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2006",
    Floor: "20",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2006",
    Floor: "20",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2101",
    Floor: "21",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2101",
    Floor: "21",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2102",
    Floor: "21",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2102",
    Floor: "21",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2103",
    Floor: "21",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2103",
    Floor: "21",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2104",
    Floor: "21",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2104",
    Floor: "21",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2105",
    Floor: "21",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2105",
    Floor: "21",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2106",
    Floor: "21",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2106",
    Floor: "21",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2201",
    Floor: "22",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2201",
    Floor: "22",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2202",
    Floor: "22",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2202",
    Floor: "22",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2203",
    Floor: "22",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2203",
    Floor: "22",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2204",
    Floor: "22",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2204",
    Floor: "22",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2205",
    Floor: "22",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2205",
    Floor: "22",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2206",
    Floor: "22",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2206",
    Floor: "22",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2301",
    Floor: "23",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2301",
    Floor: "23",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2302",
    Floor: "23",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2302",
    Floor: "23",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2303",
    Floor: "23",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2303",
    Floor: "23",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2304",
    Floor: "23",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2304",
    Floor: "23",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2305",
    Floor: "23",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2305",
    Floor: "23",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2306",
    Floor: "23",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2306",
    Floor: "23",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2401",
    Floor: "24",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2401",
    Floor: "24",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2402",
    Floor: "24",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2402",
    Floor: "24",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2403",
    Floor: "24",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2403",
    Floor: "24",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2404",
    Floor: "24",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2404",
    Floor: "24",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2405",
    Floor: "24",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2405",
    Floor: "24",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2406",
    Floor: "24",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2406",
    Floor: "24",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2501",
    Floor: "25",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2501",
    Floor: "25",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2502",
    Floor: "25",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2502",
    Floor: "25",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2503",
    Floor: "25",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2504",
    Floor: "25",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2504",
    Floor: "25",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2505",
    Floor: "25",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2505",
    Floor: "25",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2506",
    Floor: "25",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2506",
    Floor: "25",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2601",
    Floor: "26",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2601",
    Floor: "26",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2602",
    Floor: "26",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2602",
    Floor: "26",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2603",
    Floor: "26",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2603",
    Floor: "26",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2604",
    Floor: "26",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2604",
    Floor: "26",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2605",
    Floor: "26",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2605",
    Floor: "26",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2606",
    Floor: "26",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2606",
    Floor: "26",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2701",
    Floor: "27",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2701",
    Floor: "27",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2702",
    Floor: "27",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2702",
    Floor: "27",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2703",
    Floor: "27",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2703",
    Floor: "27",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2704",
    Floor: "27",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2704",
    Floor: "27",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2705",
    Floor: "27",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2705",
    Floor: "27",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2706",
    Floor: "27",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2706",
    Floor: "27",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2801",
    Floor: "28",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2801",
    Floor: "28",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2802",
    Floor: "28",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2802",
    Floor: "28",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2803",
    Floor: "28",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2803",
    Floor: "28",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2804",
    Floor: "28",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2804",
    Floor: "28",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2805",
    Floor: "28",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2805",
    Floor: "28",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2806",
    Floor: "28",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2806",
    Floor: "28",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2901",
    Floor: "29",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2901",
    Floor: "29",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2902",
    Floor: "29",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2902",
    Floor: "29",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2903",
    Floor: "29",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2903",
    Floor: "29",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2904",
    Floor: "29",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2904",
    Floor: "29",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2905",
    Floor: "29",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2905",
    Floor: "29",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "2906",
    Floor: "29",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2906",
    Floor: "29",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3001",
    Floor: "30",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "3001",
    Floor: "30",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3002",
    Floor: "30",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "3002",
    Floor: "30",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "3003",
    Floor: "30",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "3004",
    Floor: "30",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3004",
    Floor: "30",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "3005",
    Floor: "30",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3005",
    Floor: "30",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "3006",
    Floor: "30",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3006",
    Floor: "30",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "2906",
    Floor: "31",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "3101",
    Floor: "31",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3101",
    Floor: "31",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3102",
    Floor: "31",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "3102",
    Floor: "31",
    Type: "4 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "3103",
    Floor: "31",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3103",
    Floor: "31",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "3104",
    Floor: "31",
    Type: "3 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3104",
    Floor: "31",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "3105",
    Floor: "31",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3105",
    Floor: "31",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "2",
    Unit: "3106",
    Floor: "31",
    Type: "3 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3201",
    Floor: "32",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3202",
    Floor: "32",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3203",
    Floor: "32",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3204",
    Floor: "32",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3205",
    Floor: "32",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3206",
    Floor: "32",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3301",
    Floor: "33",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3302",
    Floor: "33",
    Type: "3.5 BHK Supreme",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3303",
    Floor: "33",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3304",
    Floor: "33",
    Type: "2 BHK Royal",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3305",
    Floor: "33",
    Type: "2 BHK Grand",
    Status: "Unsold",
  },
  {
    Building: "3",
    Unit: "3306",
    Floor: "33",
    Type: "2 BHK Prime",
    Status: "Unsold",
  },
];
