const BankNames = [
  { id: "ABF", name: "Aditya Birla Finance" },
  { id: "ABN AMRO", name: "ABN AMRO Bank" },
  { id: "ACE", name: "ACE Co-operative Bank Ltd" },
  { id: "ADCB", name: "Abu Dhabi Commercial Bank" },
  { id: "ALLAHABAD", name: "Allahabad Bank" },
  { id: "ABHYUDAYA", name: "Abhyudaya Bank" },
  { id: "AHMEDNAGAR", name: "Ahmednagar Merchant Co.op  Bank" },
  { id: "AJINKYATAR", name: "Ajinkyatara Mahila Sahakari Bank Ltd.Satara" },
  { id: "ANDHRA", name: "Andhra Bank" },
  { id: "ARMY", name: "Army Group Insurance Fund" },
  { id: "AXIS", name: "Axis Bank" },
  { id: "AUSFB", name: "AU Small Finance Bank" },
  { id: "BANDHAN", name: "Bandhan Bank" },
  { id: "BOI", name: "Bank Of India" },
  { id: "BOM", name: "Bank of Maharashtra" },
  { id: "BAJAJ", name: "Bajaj finance" },
  { id: "BARCLAYS", name: "Barclays Bank" },
  { id: "BOB", name: "Bank of Baroda" },
  { id: "BHARAT", name: "Bharat Bank" },
  { id: "BLANK", name: "Not yet decided" },
  { id: "BOMBAY", name: "Bombay Mercantile co-operative Bank Ltd." },
  { id: "CAPITAL", name: "Capital First" },
  { id: "CBI", name: "Central Bank of India" },
  { id: "CB", name: "Canara Bank" },
  { id: "CITI", name: "Citi Bank" },
  { id: "CITIZEN", name: "Citizen Credit Co-operative Bank Ltd." },
  { id: "CORP", name: "Corporation Bank" },
  { id: "COSMOS", name: "The Cosmos Co-operative Bank LTD" },
  { id: "DBS", name: "DBS Bank Ltd." },
  { id: "DCB", name: "DCB Bank" },
  { id: "DEB", name: "DEB Bank" },
  { id: "DENA", name: "Dena Bank" },
  { id: "DEUTSCHE", name: "Deutsche Bank" },
  { id: "DEWAN", name: "Dewan Housing Finance Ltd Bank" },
  { id: "DHIWANI", name: "Dhiwani Bank" },
  { id: "DHANLAXMI", name: "Dhanlaxmi Bank" },
  { id: "EHFL", name: "EDELWEISS HOUSING FINANCE LIMITED" },
  { id: "ESFB", name: "Equitas Small Finance Bank" },
  { id: "FEDERAL", name: "Federal Bank" },
  { id: "FIRST BLUE", name: "First Blue Home Finance Ltd." },
  { id: "GREATER", name: "GREATER BANK" },
  { id: "HABIB", name: "Habib Exchange Company L.L.C" },
  { id: "HDFC", name: "HDFC Bank" },
  { id: "HSBC", name: "HSBC Bank" },
  { id: "ICICI", name: "ICICI Bank" },
  { id: "IDBI", name: "IDBI Bank" },
  { id: "IDFC", name: "IDFC Bank" },
  { id: "IIB", name: "IndusInd Bank" },
  { id: "IIFL", name: "India Infoline" },
  { id: "INDIABULLS", name: "India Bulls" },
  { id: "ING VYSYA", name: "ING Vysya" },
  { id: "IOB", name: "Indian Overseas Bank" },
  { id: "INDIAN", name: "Indian bank" },
  { id: "INDUSIND", name: "IndusInd bank" },
  { id: "INDUSTRIAL", name: "Industrial Development Bank Of India Limited" },
  { id: "JALGAON", name: "Jalgaon Peoples Co-op Bank" },
  { id: "JKB", name: "Jammu & Kashmir Bank" },
  { id: "JANASEVA", name: "Janaseva Sahakari Bank" },
  { id: "JANKALYAN", name: "Jankalyan Sahakari Bank" },
  { id: "JANTA", name: "Janta Sahkari Bank" },
  { id: "KVB", name: "Karur Vysya Bank" },
  { id: "KB", name: "Karnataka Bank" },
  { id: "KOTAK", name: "Kotak Mahindra Bank" },
  { id: "L&T", name: "L&T" },
  { id: "LIC", name: "LIC Housing Finance Ltd" },
  { id: "LSBL", name: "Lokseva Sahakari Bank Limited" },
  { id: "LONAVLA", name: "Lonavla Sahakari Bank Ltd" },
  { id: "LVB", name: "Lakshmi Vilas Bank" },
  { id: "MSBL", name: "Mahesh Sahkari Bank Ltd" },
  { id: "MUSTAFA", name: "Mustafa Sultan Exchange Co. L.L.C" },
  { id: "NAINITAL", name: "Nainital Bank" },
  { id: "NKGSB", name: "NKGSB Co-op Bank Ltd." },
  { id: "OBC", name: "Oriental Bank Of Commerce" },
  { id: "PSB", name: "Punjab and Sind Bank" },
  { id: "PMC BANK", name: "PMC Bank" },
  { id: "POSB", name: "Post Office Savings Bank" },
  { id: "PUNE DISTR", name: "Pune District Central Co-op Bank Ltd." },
  { id: "PUNE PEOPL", name: "Pune Peoples Co-op Bank Ltd." },
  { id: "PNB", name: "Punjab National Bank" },
  { id: "RBL", name: "RBL Bank" },
  { id: "RBS BANK", name: "RBS Bank" },
  { id: "RELIANCE", name: "Reliance Home Finance" },
  { id: "RELIGARE", name: "Religare Bank" },
  { id: "SBH", name: "State Bank of Hyderabad" },
  { id: "SBI", name: "State Bank Of India" },
  { id: "SBM", name: "State Bank of Mysore" },
  { id: "SBP", name: "State Bank Of Patiala" },
  { id: "SBT", name: "State Bank of Trauancore" },
  { id: "SCB", name: "Standard Chartered Bank" },
  { id: "SIB", name: "South Indian Bank" },
  { id: "SANGLI", name: "Sangli Urban Co-op Bank Ltd." },
  { id: "SARASWAT", name: "Saraswat Bank" },
  { id: "SCOTIA", name: "Scotiabank" },
  { id: "SHAMRAO", name: "Shamrao Vithal Co-Op. Bank Ltd." },
  { id: "SBB&J", name: "Sate bank of Bikaner and Jaipur" },
  { id: "SUVARNAYUG", name: "Suvarnayug Sahakari Bank Ltd" },
  { id: "SYNDICATE", name: "Syndicate Bank" },
  { id: "TMBL", name: "Tamilnad Mercantile Bank Limited" },
  { id: "TATA", name: "TATA Capital Housing Finance" },
  { id: "THE AHMEDN", name: "The Ahmednagar Merchant’s Co-op. Bank Ltd." },
  { id: "THE AKOLA", name: "The Akola Urban Coop Bank" },
  { id: "THE COSMOS", name: "The Cosmos Co-Operative Bank Ltd." },
  { id: "THE GOA", name: "The Goa Urban co-operative bank Ltd." },
  { id: "THE KALYAN", name: "The Kalyan Janta Sahakari Bank Ltd." },
  { id: "THE KARAD", name: "The Karad Urban Co-op Bank Ltd." },
  { id: "THE MUSLIM", name: "The Muslim Co-operative Bank Ltd" },
  {
    id: "THE NASIK",
    name: "The Nasik District Central Co-Operative Bank Ltd.",
  },
  { id: "THE PANDHA", name: "The Pandharpur Urban Co-op Bank Ltd." },
  { id: "THE RATNAK", name: "The Ratnakar Bank Ltd" },
  { id: "THE ROYAL", name: "The Royal Bank of Scotland" },
  { id: "THE SEVA", name: "The Seva Vikas CO- OP. Bank Ltd." },
  { id: "THE SOUTH", name: "The South Indian Bank Ltd." },
  { id: "THE THANE", name: "The Thane Janta Sahakari Bank Ltd." },
  { id: "THE VISHWE", name: "The Vishweshwar sahakari Bank Ltd" },
  { id: "THE LATUR", name: "The latur urban co-op bank ltd" },
  { id: "UBI", name: "Union Bank of India" },
  { id: "UCO", name: "UCO Bank" },
  { id: "UTI", name: "UTI Bank Ltd." },
  { id: "UNBI", name: "United Bank of India" },
  { id: "VIDYA", name: "Vidya Sahakari Bank Ltd" },
  { id: "VIJAYA", name: "Vijaya Bank" },
  { id: "YES", name: "YES bank" },
  { id: "CATHOLIC", name: "The Catholic Syrian Bank Ltd." },
  { id: "PARSIK", name: "GP PARSIK BANK" },
  { id: "WOMENCO", name: "The Women's Co-operative Bank Ltd." },
  { id: "BICHOLIMCO", name: "The Bicholim Co-operative Bank Ltd." },
  { id: "RATNAKAR", name: "Ratnakar Bank Ltd." },
  { id: "GOACO", name: "The Goa State Co – operative Bank Ltd." },
  { id: "DECCAN", name: "The Deccan Merchants Co – op. Bank Ltd." },
];

const PaymentMode = [
  { id: "CH", name: "Cheque" },
  { id: "DD", name: "Demand Draft" },
  { id: "IMPS", name: "IMPS" },
  { id: "RTGS", name: "RTGS" },
  { id: "NEFT", name: "NEFT" },
  { id: "CASH", name: "Cash" },
  { id: "CARD", name: "Card" },
];

const PaymentTowards = [
  { id: "UNIT", name: "Flat/Unit" },
  { id: "CUSTOM", name: "Customisation" },
  { id: "INTEREST", name: "Penal Interest" },
  { id: "HOLDING", name: "Holding Charges" },
  { id: "TRANSFER", name: "Transfer Charges" },
  { id: "GST", name: "Flat/Unit GST" },
  { id: "CUSTOM_GST", name: "Customisation GST" },
  { id: "INTEREST_GST", name: "Penal Interest GST" },
  { id: "HOLDING_GST", name: "Holding Charges GST" },
  { id: "TRANSFER_GST", name: "Transfer Charges GST" },
  { id: "ST", name: "Service Tax" },
  { id: "TDS", name: "TDS" },
];

const PrintDocument = [
  { id: "BANKA", name: "Bank Allotment" },
  { id: "SOA", name: "Statement of Account" },
  { id: "INT", name: "Interest Calculation" },
  { id: "AGREEMENT", name: "Agreement Draft" },
  { id: "BANKS", name: "Bank Scheme" },
  { id: "WARRANTY", name: "Warranty Agreement" },
];

const NocDocument = [
  { id: "MOR_HDFC", name: "Mortgage NOC(HDFC)" },
  { id: "MOR_BAJAJ", name: "Mortgage NOC(Bajaj)" },
  { id: "MOR_ICICI", name: "Mortgage NOC(ICICI)" },
  { id: "CFNOCR", name: "CF NOC Request" },
  { id: "CFNOC", name: "CF NOC Approval" },
];

const letterDocument = [
  { id: "ACCEPT", name: "Acceptance Letter" },
  { id: "REJECT", name: "Rejection Letter" },
  { id: "POSSESSION", name: "Possession Letter" },
  { id: "CARPARK", name: "Carpark Letter" },
  { id: "CONFIRM", name: "Confirmation Letter" },
];

const preRegistrationMail = [
  { id: "ACCEPT", name: "Acceptance Letter" },
  { id: "AGREEMENT", name: "Agreement Draft" },
  { id: "REJECT", name: "Rejection Letter" },
  { id: "REGISTER_REMIND", name: "Registration Reminder" },
];

const prePossessionMail = [
  { id: "CONNECT1", name: "Customer Connect 1" },
  { id: "CONNECT2", name: "Customer Connect 2" },
  { id: "CONNECT3", name: "Customer Connect 3" },
  { id: "SOA", name: "Statement of Account" },
  { id: "INTEREST_LETTER", name: "Interest Letter" },
  { id: "CONGRAT_REGISTER", name: "Congratulate after Registration" },
  { id: "PAYMENT_REMINDER", name: "Payment Reminder" },
  { id: "POSSESSION_INTIMATE", name: "Intimation of Possession" },
  { id: "POSSESSION_INVITE", name: "Possession Invitation" },
  { id: "POSSESSION_REMINDER", name: "Possession Reminder" },
];

const RegistrationInviteContact = [
  { Name: "Alex Sagayam", contact: "9922952459" },
  { Name: "Vijay Kumbhar", contact: "7722018936" },
  { Name: "Nilesh Pathak", contact: "8888874809" },
];

const MaritalStatus = [
  { Id: "1", Name: "Single" },
  { Id: "2", Name: "Married" },
  { Id: "3", Name: "Widowed" },
  { Id: "4", Name: "Divorced" },
  { Id: "5", Name: "Separated" },
];

const Gender = [
  { Id: " ", Name: "Unknown" },
  { Id: "1", Name: "Female" },
  { Id: "2", Name: "Male" },
];

const HaveChildren = [
  { Id: "01", Name: "Yes" },
  { Id: "02", Name: "No" },
  { Id: "03", Name: "Not Provided" },
];

const IntrogativeQueConstant = [
  { Id: "X", Name: "Yes" },
  { Id: "N", Name: "No" },
];

const Warranty_Extension = [
  { Id: "SALES", Name: "SALES" },
  { Id: "AGREEMENT", Name: "AGREEMENT" },
  { Id: "POSSESSION", Name: "POSSESSION" },
  { Id: "POSTPOSSES", Name: "POSTPOSSES" },
];

const SelfFundingConstant = [
  { Id: "1", Name: "Payment as per STANDARD Schedule" },
  { Id: "2", Name: "Bulk Payment" },
  { Id: "3", Name: "Customised Payment Schedule" },
];

const PurchaseReasonConstant = [
  { Id: "1", Name: "Self Use" },
  { Id: "2", Name: "Investment" },
];

const exportDefault = {
  Gender,
  BankNames,
  PaymentMode,
  NocDocument,
  HaveChildren,
  PrintDocument,
  MaritalStatus,
  letterDocument,
  PaymentTowards,
  prePossessionMail,
  Warranty_Extension,
  SelfFundingConstant,
  preRegistrationMail,
  IntrogativeQueConstant,
  PurchaseReasonConstant,
  RegistrationInviteContact,
};

export default exportDefault;
